### PR TITLE
Scaffold and frame

### PR DESCRIPTION
**Pull request by FlatBallFlyer**
Everything is written - and unit testing is ~complete

### CODE REVIEW

**Review by MyNameIsAndrew-Mangix — CHANGES_REQUESTED** [review]
This refactor broke the imports, they're looking for directories (and in turn, files) that don't exist. This makes 7 of the 8 test suites fail

**Comment by FlatBallFlyer** [comment]
I think they should all work now.

**Comment by FlatBallFlyer** [comment]
Whew - what a Rabit hole that was.... git and case-sensitive file / folder names is a mess. Lesson learned, get file/folder case names right the first time!

**Review by MyNameIsAndrew-Mangix — APPROVED** [review]

**Comment by MyNameIsAndrew-Mangix** [comment]
It works on my machine 👍

**Pull request merged**
